### ISSUE TITLE
Broken linkedin link

### ISSUE THREAD

**Issue by Nauja** [juanwolf/blog.juanwolf.fr#11]
Everytime I click on the linkedin link I get a 404 error. I guess the link may be outdated and should be fixed ASAP. 
Note that your website redirect to [https://www.linkedin.com/profile/view?id=218328783](https://www.linkedin.com/profile/view?id=218328783) while the correct link is [https://www.linkedin.com/in/jean-loup-adde-81314b61](https://www.linkedin.com/in/jean-loup-adde-81314b61) .

**Comment by juanwolf** [comment]
Thanks a lot, I will change that in the next release.
