### ISSUE TITLE
Author's age is out of date and not updating automatically

### ISSUE THREAD

**Issue by Natsirtt** [juanwolf/blog.juanwolf.fr#8]
I noticed the production website is displaying the sentence "I'm Jean-Loup Adde, a 23 year old web developer", which is not correct.

It would probably be easy to make that information dynamic so that it will **always** be the right value, instead of having to update it on the author's birthday every year.

**Comment by juanwolf** [comment]
That's a great idea. For the version 2.0 I attend to use django for the whole website so this feature would be definitely in it. I was against this idea the time that this page was only HTML, that would have been a dodgy script in javascript changing the value... Not nice.
