### ISSUE TITLE
Wrong job position.

### ISSUE THREAD

**Issue by Natsirtt** [juanwolf/blog.juanwolf.fr#9]
I noticed the production website displays the sentence "a [...] web developer at Airinov" which is not correct.

That information is out of date ; but it would probably be easy to make that info dynamic so that it doesn't need to be updated every time the author changes job position or company.

**Comment by juanwolf** [comment]
Hi @Natsirtt,

# HOW DO YOU KNOW THAT

**Comment by Natsirtt** [comment]
Hello @juanwolf,

_this is not relevant, the important thing **is th**at this is a bug, and it_ 

> should

**be** fixed

**Comment by Natsirtt** [comment]
I don't understand why such a simple issue got out of the QA issue process pipeline as "won't fix".
Are you professionals even?

**Comment by juanwolf** [comment]
The development team said that's **not important at all** and might be solved for the 3.0 milestone. The QA is actually quite busy trying to install VIM on windows.

Kind regards,
@juanwolf CTO of juanwolf.fr
